name: clang-tidy-annotate

on:
  workflow_run:
    workflows: ["clang-tidy-review"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.14.0
        id: annotate
        with:
          lgtm_comment_body: ''
          annotations: true
          max_comments: 10
      - if: steps.annotate.outputs.total_comments != 0
        # Fail if there are any annotations.
        run: exit 1
